# Generated by Django 4.0 on 2021-12-23 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('customer', '0002_alter_customer_phone_number'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('attendance_description', models.CharField(max_length=500)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_id', to='customer.customer')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_id', to='employee.employee')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_id', to='service.service')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
