# Generated by Django 4.0 on 2021-12-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='service_id',
            new_name='service',
        ),
    ]
